/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 * @type {import('@docusaurus/plugin-content-docs').SidebarConfig}
 */
const sidebars = {
  gettingStarted: [
    'intro',
    'basics/whatisCSS',
    'basics/composition',
    'basics/selector',
    'basics/values-units',
    'basics/layout',
    'basics/responsive',
    'basics/devtools',
    'basics/compatibility',
    'basics/performance',
    'basics/replaced-forms',
  ],
  concepts: [
    'concepts/intro',
    'concepts/cascade',
    'concepts/specificity',
    'concepts/inheritance',
    'concepts/box-model',
    'concepts/normal-flow',
    'concepts/containing-block',
    'concepts/stacking-context',
    'concepts/layout-context',
    'concepts/formatting-context',
    'concepts/block-formatting-context',
    'concepts/flex-formatting-context',
    'concepts/grid-formatting-context',
    'concepts/color-space',
    'concepts/color-models',
    'concepts/opacity',
    'concepts/blend-mode',
    'concepts/transform-origin',
    'concepts/animation-timing',
    'concepts/easing-function',
  ],
  reference: {
    'CSS 属性': [
      'reference/properties/animation',
      'reference/properties/border',
      'reference/properties/color',
      'reference/properties/display',
      'reference/properties/position',
      'reference/properties/typography',
    ],
    'CSS 规则': [
      'reference/rules/charset',
      'reference/rules/document',
      'reference/rules/font-face',
      'reference/rules/media',
      'reference/rules/keyframes',
      'reference/rules/supports',
    ],
    'CSS 函数': [
      'reference/functions/calc()',
      'reference/functions/attr()',
      'reference/functions/rgb()',
      'reference/functions/rgba()',
      'reference/functions/hsl()',
      'reference/functions/hsla()',
      'reference/functions/linear-gradient()',
      'reference/functions/radial-gradient()',
      'reference/functions/repeating-linear-gradient()',
      'reference/functions/repeating-radial-gradient()',
      'reference/functions/rotate()',
      'reference/functions/translate()',
      'reference/functions/scale()',
      'reference/functions/skew()',
      'reference/functions/matrix()',
      'reference/functions/circle()',
      'reference/functions/ellipse()',
      'reference/functions/polygon()',
      'reference/functions/inset()',
    ],
    'CSS 数据类型': [
      'reference/data-types/integer',
      'reference/data-types/number',
      'reference/data-types/percentage',
      'reference/data-types/length',
      'reference/data-types/angle',
      'reference/data-types/time',
      'reference/data-types/frequency',
      'reference/data-types/resolution',
      'reference/data-types/string',
      'reference/data-types/url',
      'reference/data-types/color',
      'reference/data-types/image',
      'reference/data-types/custom-ident',
      'reference/data-types/inherit',
      'reference/data-types/initial',
      'reference/data-types/revert',
      'reference/data-types/unset',
      'reference/data-types/any-value',
    ],
    '伪类与伪元素': [
      'reference/pseudo-class/intro',
      'reference/pseudo-class/active',
      'reference/pseudo-class/hover',
      'reference/pseudo-class/focus',
      'reference/pseudo-class/visited',
      'reference/pseudo-class/link',
      'reference/pseudo-class/any-link',
      'reference/pseudo-class/local-link',
      'reference/pseudo-class/target',
      'reference/pseudo-class/checked',
      'reference/pseudo-class/disabled',
      'reference/pseudo-class/enabled',
      'reference/pseudo-class/default',
      'reference/pseudo-class/valid',
      'reference/pseudo-class/invalid',
      'reference/pseudo-class/required',
      'reference/pseudo-class/optional',
      'reference/pseudo-class/in-range',
      'reference/pseudo-class/out-of-range',
      'reference/pseudo-class/read-only',
      'reference/pseudo-class/read-write',
      'reference/pseudo-class/placeholder-shown',
      'reference/pseudo-class/pattern-mismatch',
      'reference/pseudo-class/indeterminate',
      'reference/pseudo-class/blank',
      'reference/pseudo-class/root',
      'reference/pseudo-class/empty',
      'reference/pseudo-class/first-child',
      'reference/pseudo-class/last-child',
      'reference/pseudo-class/nth-child',
      'reference/pseudo-class/nth-last-child',
      'reference/pseudo-class/first-of-type',
      'reference/pseudo-class/last-of-type',
      'reference/pseudo-class/nth-of-type',
      'reference/pseudo-class/only-of-type',
      'reference/pseudo-class/only-child',
      'reference/pseudo-class/scope',
      'reference/pseudo-class/dir()',
      'reference/pseudo-class/lang()',
      'reference/pseudo-class/fullscreen',
      'reference/pseudo-class/left',
      'reference/pseudo-class/right',
      'reference/pseudo-class/is()',
      'reference/pseudo-class/where()',
      'reference/pseudo-class/has()',
      'reference/pseudo-class/not()',
    ],
  },
};

module.exports = sidebars;